ui_kernel_showcase:
  path: /ui-kernel/showcase
  controller: Symfinity\UiKernel\Controller\ShowcaseController::show
  methods: [GET]

ui_kernel_theme_css:
  path: /_ui/theme.css
  controller: Symfinity\UiKernel\Controller\ShowcaseController::themeCss
  methods: [GET]

ui_kernel_showcase_js:
  path: /ui-kernel/showcase.js
  controller: Symfinity\UiKernel\Controller\ShowcaseController::showcaseScript
  methods: [GET]
